[package]
name = "rust_rayt_study"
version = "0.1.0"
authors = ["ishiiyuki <mizuki.yuuri@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
rayon = "1.5.0"
rand = "0.8.3"
